### ISSUE TITLE
Organize baked-in alerts into groups

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-k8s-operator#182]
### Enhancement Proposal

Currently we're using the "one rule per file" format.

Seems like it would be easier to manager if they were organized into groups:
```yaml
groups:
- name: COSLiteBakedIn_LokiIsDown
  rules:
  - alert: LokiProcessTooManyRestarts_LowFreq
    expr: changes(process_start_time_seconds[15m]) > 5
  - alert: LokiProcessTooManyRestarts_HighFreq
    expr: changes(process_start_time_seconds[2m]) > 5
  - alert: LokiIsDown
    expr: (something to do with "up")
```

Advantages:
- Relevant alerts are next to each other (can immediately see if we need `LokiProcessTooManyRestarts_HighFreq` if we already have `LokiIsDown`)
- Potentially in the future could inhibit alerts by a group matcher (related: https://github.com/prometheus/alertmanager/issues/2984)
- Use the standard file format (one rule per file is a COS Lite custom format)
