### ISSUE TITLE
Plot log growth rate in Grafana

### ISSUE THREAD

**Issue by simskij** [canonical/loki-k8s-operator#220]
### Enhancement Proposal

Add the following panels to the Loki Grafana Dashboard:

- Predict when the disk is full
- Plot log growth rate

**Comment by simskij** [comment]
We need to investigate whether this is possible with the metrics currently provided by Loki.

**Comment by simskij** [comment]
We could also make an alert rule for this.

**Comment by Abuelodelanada** [comment]
## Research log

### 12/04/2024

**Useful metrics**
- `loki_distributor_bytes_received_total`: *"The total number of uncompressed bytes received per tenant. Includes structured metadata bytes."*

   We have a Panel named "Distributor Received bytes / sec" that uses this metric.

   ```
   sum by(tenant)(rate(loki_distributor_bytes_received_total{juju_application=~"$juju_application",juju_model=~"$juju_model",juju_model_uuid=~"$juju_model_uuid",juju_unit=~"$juju_unit"}[5m]))
   ```


- `loki_ingester_chunk_utilization`: *"Distribution of stored chunk utilization (when stored)."*
- `loki_ingester_chunk_stored_bytes_total`: *"Total bytes stored in chunks per tenant."*


   We have a panel named *"Store Chunks total:"* that uses this metric:

   ```
   sum(loki_ingester_chunk_stored_bytes_total{juju_application=~"$juju_application",juju_model=~"$juju_model",juju_model_uuid=~"$juju_model_uuid",juju_unit=~"$juju_unit"})
   ```
   
- Loki does not provide a metric to predict when the disk is full. For instance, the Loki charm has defined two storages:

   ```yaml
   storage:
     active-index-directory:
       type: filesystem
       description: Mount point in which Loki will store index
     loki-chunks:
       type: filesystem
       description: Mount point in which Loki will store chunks (objects)
   ```
   And in a Loki deployment we can see:

   ```shell
   root@loki-0:/# mount | grep "/loki"
   /dev/sda1 on /loki/boltdb-shipper-active type ext4 (rw,relatime,discard,errors=remount-ro)
   /dev/sda1 on /loki/chunks type ext4 (rw,relatime,discard,errors=remount-ro)
   
   
   root@loki-0:/# df -h /loki
   Filesystem      Size  Used Avail Use% Mounted on
   overlay          49G   44G  4.7G  91% /
   ```
