### ISSUE TITLE
Wrong label matching operator added to loki alert rules expr

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#228]
### Bug Description

The method `_from_file()` in class `AlertRules` [adds `job=".+"`](https://github.com/canonical/loki-k8s-operator/blob/main/lib/charms/loki_k8s/v0/loki_push_api.py#L769).

We are using a regex: `.+` with a wrong [label matching operator](https://grafana.com/docs/loki/latest/logql/log_queries/#log-stream-selector): `"=": exactly equal`.
We should use: `"=~": regex matches`

### To Reproduce

1. In a charm that `requires` the `logging` relation (`loki_push_api` interface), create an alert rule file and place it in `src/loki_alert_rules`. For instance:
```yaml
   alert: ErrorLevelLogsFound
   expr: rate({%%juju_topology%%} |= "level=error"[1m]) > 0
   for: 1m
   labels:
     severity: critical
   annotations:
   summary: error level logs found.
```
3. Pack the charm.
4. Deploy Loki, and the charm
5. Relate both charms.
6. Check that in the loki container the alert rules files has the juju topology, and the wrong label filter: `job=".+"`. In our example, the rule file will be:
```shell
/loki/rules/fake # cat cos_381236d6_traefik_alert.rules
groups:
- name: cos_381236d6_traefik_error_level_logs_found_alerts
  rules:
  - alert: ErrorLevelLogsFound
    annotations:
      summary: error level logs found.
    expr: (rate({job=".+", juju_application="traefik", juju_charm="traefik-k8s", juju_model="cos",
      juju_model_uuid="381236d6-8c63-4415-80ad-bfdccc1ddb4c"} |= "level=error"[1m])
      > 0)
    for: 1m
    labels:
      juju_application: traefik
      juju_charm: traefik-k8s
      juju_model: cos
      juju_model_uuid: 381236d6-8c63-4415-80ad-bfdccc1ddb4c
      severity: critical
```

### Environment

- LIBPATCH = 13

### Relevant log output

```shell
-
```
