### ISSUE TITLE
Log forwarding stops after pod restart

### ISSUE THREAD

**Issue by markbeierl** [canonical/loki-k8s-operator#358]
### Bug Description

If a pod is terminated outside of Juju's scope, such as pod eviction, when the new pod starts, Pebble no longer has the `log-targets` layer.

### To Reproduce

1. juju deploy a charm that has log forwarding (`juju deploy score-ausf-k8s --channel=1.3/edge`)
2. Deploy Grafana agent, relate it to the charm
3. Show the pebble plan. Note the `log-targets`
4. Kill the pod (`kubectl delete po -n control-plane sdcore-ausf-k8s-0`)
5. Show the pebble plan. Note the lack of `log-targets`

### Environment

Charm: https://github.com/canonical/sdcore-ausf-k8s-operator/blob/main/src/charm.py#L60
LIBPATCH of loki_push_api: 4

Juju: 3.4.0-genericlinux-amd64
Controller: 3.4.0

Microk8s: v1.29.2 strict

### Relevant log output

```shell
Initial startup pebble plan:

ubuntu@control-plane:~$ kubectl exec -tin control-plane -c ausf ausf-0 -- pebble plan
services:
    ausf:
        startup: enabled
        override: replace
        command: /bin/ausf --ausfcfg /free5gc/config/ausfcfg.conf
        environment:
            GOTRACEBACK: crash
            GRPC_GO_LOG_SEVERITY_LEVEL: info
            GRPC_GO_LOG_VERBOSITY_LEVEL: "99"
            GRPC_TRACE: all
            GRPC_VERBOSITY: DEBUG
            MANAGED_BY_CONFIG_POD: "true"
            POD_IP: 10.1.235.159
log-targets:
    grafana-agent/0:
        type: loki
        location: http://grafana-agent-0.grafana-agent-endpoints.control-plane.svc.cluster.local:3500/loki/api/v1/push
        services:
            - all
        override: replace
        labels:
            charm: sdcore-ausf-k8s
            juju_application: ausf
            juju_model: control-plane
            juju_model_uuid: 60fc7414-58e5-4e79-8588-0301cd7ffaf7
            juju_unit: ausf/0
            product: Juju
```

After restarting pod:
```
ubuntu@control-plane:~$ kubectl exec -tin control-plane -c ausf ausf-0 -- pebble plan
services:
    ausf:
        startup: enabled
        override: replace
        command: /bin/ausf --ausfcfg /free5gc/config/ausfcfg.conf
        environment:
            GOTRACEBACK: crash
            GRPC_GO_LOG_SEVERITY_LEVEL: info
            GRPC_GO_LOG_VERBOSITY_LEVEL: "99"
            GRPC_TRACE: all
            GRPC_VERBOSITY: DEBUG
            MANAGED_BY_CONFIG_POD: "true"
            POD_IP: 10.1.235.171
```
```


### Additional context

_No response_
