### ISSUE TITLE
Allow configuration of loki

### ISSUE THREAD

**Issue by honghan-wong** [canonical/loki-k8s-operator#369]
### Bug Description

With regards to bug #362, we would like to have a configurable loki where we can modify the retention or compactor.
We dont see any retention in the current loki deployment and would like to have option to set the compactor + retention.

The loki is running on v2.7.4
```bash
$ curl localhost:3100/loki/api/v1/status/buildinfo
{"version":"2.7.4","revision":"98421b0c0","branch":"HEAD","buildUser":"root@rockcraft-loki-785655","buildDate":"2023-03-26T12:09:41Z","goVersion":""}
```

https://grafana.com/docs/loki/v2.7.x/operations/storage/retention/#grafana-loki-storage-retention

### To Reproduce

See #362
```
  loki:
    charm: loki-k8s
    channel: latest/stable
    revision: 105
    resources:
      loki-image: 88
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,2048M
      loki-chunks: kubernetes,1,409600M
    trust: true
```

### Environment

running on microk8s + microceph

```
series: jammy
applications:
  microceph:
    charm: microceph
    channel: edge
    revision: 9
    num_units: 3
    constraints: arch=amd64
  microk8s:
    charm: microk8s
    channel: legacy/stable
    revision: 121
    num_units: 3
    options:
      addons: dns ingress rbac
      channel: latest/stable
      skip_verify: true
    constraints: arch=amd64
```

### Relevant log output

```shell
See #362
```
