### ISSUE TITLE
Allow Specifying retention periods for individual streams.

### ISSUE THREAD

**Issue by Osama-Kassem** [canonical/loki-k8s-operator#472]
### Enhancement Proposal

For audit compliance reasons, we'd like to keep some of our logs for an extended period of time. Currently, the charm docs say: `Specifying retention periods for individual streams is not currently supported.`.

This feature is supported by compactor using the `retention_stream` configuration: https://grafana.com/docs/loki/latest/operations/storage/retention/#retention-configuration

**Comment by sed-i** [comment]
Seem like the requirer side could expose retention period as a config option and the loki libs would render a stream selector with the requirer's juju topology.

https://grafana.com/docs/loki/latest/operations/storage/retention/#configuring-the-retention-period
```yaml
limits_config:
  retention_period: 744h
  retention_stream:
  - selector: '{namespace="dev"}'
    priority: 1
    period: 24h
```

This is still a bit risky because the requirer charm could technically provide a selector that would match other streams unintentionally.
On the provider side (loki itself) we will be able to render the selector ourselves only if we add to reldata an analogue of `scrape_metadata`, because CMRs are obfuscated.
