### ISSUE TITLE
Update Promtail files for non-root users

### ISSUE THREAD

**Issue by MichaelThamm** [canonical/loki-k8s-operator#498]
### Enhancement Proposal

From @alithethird and @jdkandersson:

As of [Juju 3.6](https://discourse.charmhub.io/t/juju-3-6-0-released/16027) Charms can have [non-root users](https://canonical-charmcraft.readthedocs-hosted.com/en/stable/reference/files/metadata-yaml-file/#charm-user). Some charm authors will want to make use of non-root charm containers. Loki creates the promtail folders ([here](https://github.com/canonical/paas-charm/blob/5bc55f828c0c649399a633e1cc368ea82631b885/examples/flask/lib/charms/loki_k8s/v0/loki_push_api.py#L1983) and [here](https://github.com/canonical/paas-charm/blob/5bc55f828c0c649399a633e1cc368ea82631b885/examples/flask/lib/charms/loki_k8s/v1/loki_push_api.py#L1999)) in the charm. The issue is that the `/opt/promtail` and `/etc/promtail` need to be owned by the daemon user. If that is not setup in the Rock beforehand, then the daemon user won't be able to create those directories and then the library fails because it tries to and can't create those directories. So a fix could be to use the /tmp directory, or perhaps the home dir of the user? Or perhaps update the docs to say the directory needs to be there with the right ownership/ access. Fix this in the rockcraft.yaml to create the folders in the rock and set the user as `_daemon_`. Consider updating the docs or the library to make it easier for users to use `non-root` charms.

```yaml
    permissions:
      - path: opt/promtail
        owner: 584792
        group: 584792
      - path: etc/promtail
        owner: 584792
        group: 584792
```
