### ISSUE TITLE
Loki push_api lib should validate alert rules have at least one equality matcher

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-k8s-operator#91]
While working on cos-config I found out that [alert rules](https://github.com/canonical/cos-configuration-k8s-operator/tree/main/tests/samples/loki_alert_rules) that I forward to Loki are rejected: Loki sees them but complains about syntax
```
> $ curl 10.152.183.14:3100/loki/api/v1/rules                                                                                                                                                              
failed to list rule group for user fake and namespace 0_cos-configuration-k8s_alert.rules: error parsing /loki/rules/fake/0_cos-configuration-k8s_alert.rules: /loki/rules/fake/0_cos-configuration-k8s_alert.rules: could not parse expression: parse error at line 1, col 1: syntax error: unexpected IDENTIFIER
```
but the only thing in line 1 is `groups:`.

Apparently,

> you need at least one equality matcher
> https://github.com/cortexproject/cortex/issues/3875#issuecomment-790530357

When I replaced the rule with the following, Loki was happy
```yaml
groups:
 - name: example
   rules:
     - alert: HighThroughputLogStreams
       expr: absent_over_time({namespace="dev",job=~".*-logs"}[2m])
       for: 2m
```
Seems like the loki lib needs to check for this so the user could be prompted.

**Comment by sed-i** [comment]
@rbarry82 do you mind submitting that `/` to `_` replacement fix?

**Comment by rbarry82** [comment]
@dstathis Probably should be pushed to avoid the path nested from units

**Comment by Abuelodelanada** [comment]
Hi @sed-i 

> When I replaced the rule with the following, Loki was happy
> 
> ```yaml
> groups:
>  - name: example
>    rules:
>      - alert: HighThroughputLogStreams
>        expr: absent_over_time({namespace="dev",job=~".*-logs"}[2m])
>        for: 2m
> ```

Do you have a previous alert rule example that fails?

**Comment by sed-i** [comment]
Any rules without equality matchers should do. I think I was using this one:
```yaml
alert: CPUOverUse
expr: process_cpu_seconds_total > 0.12
for: 0m
labels:
  severity: Low
annotations:
  summary: "Instance {{ $labels.instance }} CPU over use"
  description: "{{ $labels.instance }} of job {{ $labels.job }} has used too much CPU."
```
